name: Docker Build & Push

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: The Docker registry to use.
        required: true
      image-name:
        type: string
        description: The name of the Docker image that will be pushed to the registry.
        required: true
      username:
        type: string
        description: The username used to login to the registry.
        required: true
      tags:
        type: string
        description: A comma separated list of tags to use.
        required: true
    secrets:
      password:
        description: The password used to login to the registry.
        required: true

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}
      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ inputs.tags }}
