name: NPM Build

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: 16.x
      path:
        type: string
        description: The path to the files being linted.
        required: false
        default: .

jobs:
  npm-build:
    name: NPM Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies (ignore scripts)
        run: npm ci --ignore-scripts
      - name: Run NPM Build
        run: npm run build
        working-directory: ${{ inputs.path }}
