name: NPM Publish
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: 16.x
      registry-url:
        type: string
        description: The URL of the NPM registry to use.
        required: false
        default: https://registry.npmjs.org
      scope:
        type: string
        description: The package scope to publish under.
        required: true
      package-version:
        type: string
        description: The package version to publish under.
        required: true
      path:
        type: string
        description: The path to the files being linted.
        required: false
        default: .
    secrets:
      npm-token:
        required: true
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.scope }}
      - name: Updated Package Version
        run: |
          sed -i'.backup' -r 's/"version": "0.0.0"/"version": "${{ inputs.package-version }}"/' package.json
          sed -i'.backup' -r 's/"version": "0.0.0"/"version": "${{ inputs.package-version }}"/' package-lock.json
          rm package.json.backup
          rm package-lock.json.backup
        working-directory: ${{ inputs.paths }}
      - name: Install Dependencies (ignore scripts)
        run: npm ci --ignore-scripts
        working-directory: ${{ inputs.path }}
      - name: Run NPM Build
        run: npm run build
        working-directory: ${{ inputs.path }}
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
        working-directory: ${{ inputs.path }}
