name: NPM Lint
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: 16.x
      path:
        type: string
        description: The path where the files that will be linted are located.
        required: false
        default: .
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Change Directory
        run: cd ${{ inputs.path }}
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies (ignore scripts)
        run: npm ci --ignore-scripts
      - name: Run Prettier
        run: npm run format-check
