name: NPM Publish

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: 16.x

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
