name: Prettier

on:
  workflow_call:

jobs:
  npm-test:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.2
        with:
          dry: True
          only_changed: True
          prettier_options: --check **/*.{js,ts}
