name: Typescript Action Package
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: "16"
      dry-run:
        type: boolean
        description: Whether the packaged code should be pushed or not, defaults to false.
        required: false
        default: false

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run NCC
        run: npm run package
      - name: Push
        if: ${{ inputs.dry-run != true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "chore: automated package of dist directory"
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@millhouse.dev
          file_pattern: dist/*
