name: Typescript Action Package

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: The version of NodeJS to use, defaults to 16.x.
        required: false
        default: 16.x
      dry-run:
        type: boolean
        description: Whether the packaged code should be pushed or not, defaults to false.
        required: false
        default: false
      commit-user-name:
        type: string
        description: The name of the user making the commit.
        required: true
      commit-user-email-address:
        type: string
        description: The email address of the making the commit.

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies (ignore scripts)
        run: npm ci --ignore-scripts
      - name: Run NCC
        run: npm run package
      - name: Push
        if: ${{ inputs.dry-run != true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          commit_message: "chore: automated package of dist directory"
          commit_user_name: ${{ inputs.commit-user-name }}
          commit_user_email: ${{ inputs.commit-user-email-address }}
          file_pattern: dist/
